name: achievement
description: A new Flutter project.
homepage: https://github.com/av-ugolkov

publish_to: 'none'

version: 0.211110.2237

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

  sqflite: ^2.0.0+3
  path_provider: ^2.0.6
  image_picker: ^0.8.3+3
  flutter_local_notifications: ^8.1.1+1
  yaml: ^3.1.0
  url_launcher: ^6.0.9
  
  heatmap_calendar:
    git:
      url: https://github.com/av-ugolkov/heatmap_calendar.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
      - pubspec.yaml
      - android/app/src/main/res/drawable/icon_achievement.png
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700