name: achievement
description: A new Flutter project.
homepage: https://github.com/av-ugolkov
version: 0.241219.0042

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sqflite: ^2.0.0+3
  path_provider: ^2.0.6
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.0.9
  
  heatmap_calendar:
    git:
      url: https://github.com/av-ugolkov/heatmap_calendar.git
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
      - pubspec.yaml
      - assets/icons/icon_achievement.png
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700